# Generated by Django 5.1.7 on 2025-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
